server:
  url: '127.0.0.1:1235'

clients:
  dlv:
    host: 'localhost:50080'
  keyPoint:
    url: 'http://127.0.0.1:1234'

breakpoint:
  - filePath: '/Users/ddr/fuzz-interrupt/keypoint/injection/breakpoint.go'
    line: 3

injections:
  getFileNameWithContent:
    - type: sleep
      sleep:
        duration: 500ms